# Generated by Django 3.2.4 on 2021-07-04 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0010_alter_question_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_email',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='is_paragraph',
            field=models.BooleanField(default=False),
        ),
    ]
