# Generated by Django 3.2.4 on 2021-07-04 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0013_auto_20210704_1102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='email',
        ),
        migrations.RemoveField(
            model_name='question',
            name='passage',
        ),
    ]
