# Generated by Django 3.2.4 on 2021-07-04 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0014_auto_20210704_1106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email',
            name='email_question',
        ),
        migrations.RemoveField(
            model_name='passage',
            name='passage_question',
        ),
        migrations.AddField(
            model_name='email',
            name='email_qs',
            field=models.CharField(default=True, max_length=2500),
        ),
        migrations.AddField(
            model_name='passage',
            name='passage_qs',
            field=models.CharField(default=True, max_length=2500),
        ),
    ]
