# Generated by Django 3.2.4 on 2021-07-04 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0015_auto_20210704_1111'),
    ]

    operations = [
        migrations.RenameField(
            model_name='email',
            old_name='email_qs',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='passage',
            old_name='passage_qs',
            new_name='passage',
        ),
    ]
