# Generated by Django 3.2.4 on 2021-07-04 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0017_auto_20210704_1114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='email',
        ),
        migrations.RemoveField(
            model_name='question',
            name='passage',
        ),
        migrations.DeleteModel(
            name='Email',
        ),
        migrations.DeleteModel(
            name='Passage',
        ),
    ]
