# Generated by Django 3.2.4 on 2021-07-04 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0019_email_passage'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='email',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.email'),
        ),
        migrations.AddField(
            model_name='question',
            name='passage',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.passage'),
        ),
    ]
