# Generated by Django 3.2.4 on 2021-07-07 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0021_auto_20210706_2154'),
    ]

    operations = [
        migrations.CreateModel(
            name='LongPassage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longpassage_qs', models.CharField(max_length=3000)),
            ],
        ),
    ]
