# Generated by Django 3.2.4 on 2021-07-07 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0022_longpassage'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_email',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='is_longpassage',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='is_passage',
            field=models.BooleanField(default=False),
        ),
    ]
