# Generated by Django 3.2.4 on 2021-07-21 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0023_auto_20210707_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='email_qs',
            field=models.CharField(max_length=3000000),
        ),
        migrations.AlterField(
            model_name='longpassage',
            name='longpassage_qs',
            field=models.CharField(max_length=3000000),
        ),
        migrations.AlterField(
            model_name='passage',
            name='passage_qs',
            field=models.CharField(max_length=3000000),
        ),
    ]
